export type TokenDefinition = {
  name: string
  matcher: string | RegExp
}

export const tokenDefinitions: TokenDefinition[] = [
  { name: 'line_comment', matcher: /^\/\/.*(\r\n|\r|\n|$)/u },
  { name: 'trash_character', matcher: /^[ \t\r\n]+/u },

  { name: 'keyword_package', matcher: 'package' },
  { name: 'keyword_use', matcher: 'use' },
  { name: 'keyword_extern', matcher: 'extern' },
  { name: 'keyword_export', matcher: 'export' },
  { name: 'keyword_as', matcher: 'as' },
  { name: 'keyword_def', matcher: 'def' },
  { name: 'keyword_typ', matcher: 'typ' },
  { name: 'keyword_fun', matcher: 'fun' },
  { name: 'keyword_lit', matcher: 'lit' },
  { name: 'keyword_sym', matcher: 'sym' },
  { name: 'keyword_meta', matcher: 'meta' },
  { name: 'keyword_const', matcher: 'const' },
  { name: 'keyword_packed', matcher: 'packed' },
  { name: 'keyword_align', matcher: 'align' },
  { name: 'keyword_defer', matcher: 'defer' },
  { name: 'keyword_return', matcher: 'return' },
  { name: 'keyword_throw', matcher: 'throw' },
  { name: 'keyword_try', matcher: 'try' },
  { name: 'keyword_catch', matcher: 'catch' },
  { name: 'keyword_error', matcher: 'error' },
  { name: 'keyword_struct', matcher: 'struct' },
  { name: 'keyword_public', matcher: 'public' },
  { name: 'keyword_private', matcher: 'private' },
  { name: 'keyword_union', matcher: 'union' },
  { name: 'keyword_enum', matcher: 'enum' },
  { name: 'keyword_for', matcher: 'for' },
  { name: 'keyword_while', matcher: 'while' },
  { name: 'keyword_loop', matcher: 'loop' },
  { name: 'keyword_if', matcher: 'if' },
  { name: 'keyword_elseif', matcher: 'elseif' },
  { name: 'keyword_else', matcher: 'else' },
  { name: 'keyword_switch', matcher: 'switch' },
  { name: 'keyword_case', matcher: 'case' },
  { name: 'keyword_break', matcher: 'break' },
  { name: 'keyword_continue', matcher: 'continue' },
  { name: 'keyword_alloc', matcher: 'alloc' },
  { name: 'keyword_free', matcher: 'free' },
  { name: 'keyword_init', matcher: 'init' },
  { name: 'keyword_clear', matcher: 'clear' },
  { name: 'keyword_tmpl', matcher: 'tmpl' },
  { name: 'keyword_in', matcher: 'in' },

  { name: 'sign_;', matcher: ';' },
  { name: 'sign_:', matcher: ':' },
  { name: 'sign_=', matcher: '=' },
  { name: 'sign_.', matcher: '.' },
  { name: 'sign_->', matcher: '->' },
  { name: 'sign_(', matcher: '(' },
  { name: 'sign_)', matcher: ')' },
  { name: 'sign_,', matcher: ',' },
  { name: 'sign_...', matcher: '...' },
  { name: 'sign_${', matcher: '${' },
  { name: 'sign_{', matcher: '{' },
  { name: 'sign_}', matcher: '}' },
  { name: 'sign_<', matcher: '<' },
  { name: 'sign_>', matcher: '>' },
  { name: 'sign_[', matcher: '[' },
  { name: 'sign_]', matcher: ']' },
  { name: 'sign_..', matcher: '..' },
  { name: 'sign_@', matcher: '@' },
  { name: 'sign_$', matcher: '$' },
  { name: 'sign_::', matcher: '::' },
  { name: 'sign_{{lit', matcher: '{{lit' },
  { name: 'sign_{{sym', matcher: '{{sym' },
  { name: 'sign_{{meta', matcher: '{{meta' },
  { name: 'sign_{{eval', matcher: '{{eval' },
  { name: 'sign_{{throw', matcher: '{{throw' },
  { name: 'sign_{{opt', matcher: '{{opt' },
  { name: 'sign_{{if', matcher: '{{if' },
  { name: 'sign_{{/if', matcher: '{{/if' },
  { name: 'sign_{{for', matcher: '{{for' },
  { name: 'sign_{{/for', matcher: '{{/for' },
  { name: 'sign_}}', matcher: '}}' },
  { name: 'sign_+', matcher: '+' },
  { name: 'sign_-', matcher: '-' },
  { name: 'sign_*', matcher: '*' },
  { name: 'sign_/', matcher: '/' },
  { name: 'sign_%', matcher: '%' },
  { name: 'sign_!', matcher: '!' },
  { name: 'sign_||', matcher: '||' },
  { name: 'sign_&&', matcher: '&&' },
  { name: 'sign_^', matcher: '^' },
  { name: 'sign_~', matcher: '~' },
  { name: 'sign_|', matcher: '|' },
  { name: 'sign_&', matcher: '&' },
  { name: 'sign_==', matcher: '==' },
  { name: 'sign_!=', matcher: '!=' },
  { name: 'sign_<=', matcher: '<=' },
  { name: 'sign_>=', matcher: '>=' },
  { name: 'sign_+=', matcher: '+=' },
  { name: 'sign_-=', matcher: '-=' },
  { name: 'sign_*=', matcher: '*=' },
  { name: 'sign_/=', matcher: '/=' },
  { name: 'sign_%=', matcher: '%=' },
  { name: 'sign_^=', matcher: '^=' },
  { name: 'sign_~=', matcher: '~=' },
  { name: 'sign_|=', matcher: '|=' },
  { name: 'sign_&=', matcher: '&=' },
  { name: 'sign_<<=', matcher: '<<=' },
  { name: 'sign_>>=', matcher: '>>=' },

  { name: 'literal_string', matcher: /^"([^"\\]|\\.)*"([ \t\r\n]*"([^"\\]|\\.)*")*/u },
  { name: 'literal_char', matcher: /^'([^'\\]|\\.)'/u },
  { name: 'literal_hex_integer', matcher: /^0x[0-9A-F]+(_[0-9A-F]+)*/u },
  { name: 'literal_oct_integer', matcher: /^0o[0-7]+(_[0-7]+)*/u },
  { name: 'literal_bin_integer', matcher: /^0b[01]+(_[01]+)*/u },
  { name: 'literal_dec_integer', matcher: /^[0-9]+(_[0-9]+)*/u },
  { name: 'literal_hex_float', matcher: /^0x([0-9A-F]+(_[0-9A-F]+)*\.[0-9A-F]+(_[0-9A-F]+)*)p-?[0-9]+/u },
  { name: 'literal_dec_float', matcher: /^([0-9]+(_[0-9]+)*\.[0-9]+(_[0-9]+)*)(e-?[0-9]+)?/u },
  { name: 'literal_bool', matcher: /^true|^false/u },
  { name: 'literal_null', matcher: 'null' },

  { name: 'symbol', matcher: /^[A-Za-z_][0-9A-Za-z_]*/u },
]
