export type TokenDefinition = {
  name: string
  matcher: string | RegExp
}

export const tokenDefinitions: TokenDefinition[] = [
  { name: 'line_comment', matcher: /^\/\/.*(\r\n|\r|\n|$)/u },
  { name: 'trash_character', matcher: /^[ \t\r\n]+/u },

  { name: 'keyword_use', matcher: 'package' },
  { name: 'keyword_use', matcher: 'use' },
  { name: 'keyword_export', matcher: 'export' },
  { name: 'keyword_include', matcher: 'include' },
  { name: 'keyword_def', matcher: 'def' },
  { name: 'keyword_typ', matcher: 'typ' },
  { name: 'keyword_lit', matcher: 'lit' },
  { name: 'keyword_const', matcher: 'const' },
  { name: 'keyword_packed', matcher: 'packed' },
  { name: 'keyword_func', matcher: 'func' },
  { name: 'keyword_defer', matcher: 'defer' },
  { name: 'keyword_return', matcher: 'return' },
  { name: 'keyword_throw', matcher: 'throw' },
  { name: 'keyword_try', matcher: 'try' },
  { name: 'keyword_catch', matcher: 'catch' },
  { name: 'keyword_error', matcher: 'error' },
  { name: 'keyword_struct', matcher: 'struct' },
  { name: 'keyword_union', matcher: 'union' },
  { name: 'keyword_enum', matcher: 'enum' },
  { name: 'keyword_for', matcher: 'for' },
  { name: 'keyword_if', matcher: 'if' },
  { name: 'keyword_elesif', matcher: 'elseif' },
  { name: 'keyword_else', matcher: 'else' },
  { name: 'keyword_switch', matcher: 'switch' },
  { name: 'keyword_case', matcher: 'case' },
  { name: 'keyword_break', matcher: 'break' },
  { name: 'keyword_continue', matcher: 'continue' },
  { name: 'keyword_new', matcher: 'alloc' },
  { name: 'keyword_delete', matcher: 'free' },
  { name: 'keyword_new', matcher: 'init' },
  { name: 'keyword_delete', matcher: 'clean' },
  { name: 'keyword_template', matcher: 'template' },

  { name: 'symbol_;', matcher: ';' },
  { name: 'symbol_:', matcher: ':' },
  { name: 'symbol_=', matcher: '=' },
  { name: 'symbol_.', matcher: '.' },
  { name: 'symbol_->', matcher: '->' },
  { name: 'symbol_(', matcher: '(' },
  { name: 'symbol_)', matcher: ')' },
  { name: 'symbol_,', matcher: ',' },
  { name: 'symbol_...', matcher: '...' },
  { name: 'symbol_{', matcher: '{' },
  { name: 'symbol_}', matcher: '}' },
  { name: 'symbol_<', matcher: '<' },
  { name: 'symbol_>', matcher: '>' },
  { name: 'symbol_[', matcher: '[' },
  { name: 'symbol_]', matcher: ']' },
  { name: 'symbol_..', matcher: '..' },
  { name: 'symbol_@', matcher: '@' },
  { name: 'symbol_$', matcher: '$' },
  { name: 'symbol_::', matcher: '::' },
  { name: 'symbol_{{', matcher: '{{' },
  { name: 'symbol_}}', matcher: '}}' },
  { name: 'symbol_#{{', matcher: '#{{' },
  { name: 'symbol_+', matcher: '+' },
  { name: 'symbol_-', matcher: '-' },
  { name: 'symbol_*', matcher: '*' },
  { name: 'symbol_/', matcher: '/' },
  { name: 'symbol_%', matcher: '%' },
  { name: 'symbol_!', matcher: '!' },
  { name: 'symbol_||', matcher: '||' },
  { name: 'symbol_&&', matcher: '&&' },
  { name: 'symbol_^', matcher: '^' },
  { name: 'symbol_~', matcher: '~' },
  { name: 'symbol_|', matcher: '|' },
  { name: 'symbol_&', matcher: '&' },
  { name: 'symbol_<<', matcher: '<<' },
  { name: 'symbol_>>', matcher: '>>' },
  { name: 'symbol_==', matcher: '==' },
  { name: 'symbol_!=', matcher: '!=' },
  { name: 'symbol_<=', matcher: '<=' },
  { name: 'symbol_>=', matcher: '>=' },
  { name: 'symbol_+=', matcher: '+=' },
  { name: 'symbol_-=', matcher: '-=' },
  { name: 'symbol_*=', matcher: '*=' },
  { name: 'symbol_/=', matcher: '/=' },
  { name: 'symbol_%=', matcher: '%=' },
  { name: 'symbol_^=', matcher: '^=' },
  { name: 'symbol_~=', matcher: '~=' },
  { name: 'symbol_|=', matcher: '|=' },
  { name: 'symbol_&=', matcher: '&=' },
  { name: 'symbol_<<=', matcher: '<<=' },
  { name: 'symbol_>>=', matcher: '>>=' },

  { name: 'literal_string', matcher: /^"([^"\\]|\\.)*"([ \t\r\n]*"([^"\\]|\\.)*")*/u },
  { name: 'literal_char', matcher: /^'([^'\\]|\\.)'/u },
  { name: 'literal_hex_integer', matcher: /^0x[0-9A-F]+(_[0-9A-F]+)*/u },
  { name: 'literal_oct_integer', matcher: /^0o[0-7]+(_[0-7]+)*/u },
  { name: 'literal_bin_integer', matcher: /^0b[01]+(_[01]+)*/u },
  { name: 'literal_dec_integer', matcher: /^[0-9]+(_[0-9]+)*/u },
  { name: 'literal_hex_float', matcher: /^0x([0-9A-F]+(_[0-9A-F]+)*\.[0-9A-F]+(_[0-9A-F]+)*)p-?[0-9]+/u },
  { name: 'literal_dec_float', matcher: /^([0-9]+(_[0-9]+)*\.[0-9]+(_[0-9]+)*)(e-?[0-9]+)?/u },
  { name: 'literal_bool', matcher: /^true|^false/u },
  { name: 'literal_null', matcher: 'null' },

  { name: 'identifier', matcher: /^[A-Za-z_][0-9A-Za-z_]*/u },
]
