import { TokenDefinition } from "@/types/token-definition"

export const tokenDefinitions: TokenDefinition[] = [
  { type: "line_comment", matcher: /^\/\/.*(\r\n|\r|\n|$)/u },
  { type: "trash_character", matcher: /^[ \t\r\n]+/u },

  { type: "keyword_import", matcher: "import" },
  { type: "keyword_export", matcher: "export" },
  { type: "keyword_as", matcher: "as" },
  { type: "keyword_include", matcher: "include" },
  { type: "keyword_extern", matcher: "extern" },
  { type: "keyword_def", matcher: "def" },
  { type: "keyword_type", matcher: "type" },
  { type: "keyword_const", matcher: "const" },
  { type: "keyword_func", matcher: "func" },
  { type: "keyword_defer", matcher: "defer" },
  { type: "keyword_return", matcher: "return" },
  { type: "keyword_struct", matcher: "struct" },
  { type: "keyword_union", matcher: "union" },
  { type: "keyword_enum", matcher: "enum" },
  { type: "keyword_for", matcher: "for" },
  { type: "keyword_if", matcher: "if" },
  { type: "keyword_elesif", matcher: "elseif" },
  { type: "keyword_else", matcher: "else" },
  { type: "keyword_switch", matcher: "switch" },
  { type: "keyword_case", matcher: "case" },
  { type: "keyword_break", matcher: "break" },
  { type: "keyword_continue", matcher: "continue" },
  { type: "keyword_new", matcher: "new" },
  { type: "keyword_delete", matcher: "delete" },
  { type: "keyword_#template", matcher: "#template" },
  { type: "keyword_#if", matcher: "#if" },
  { type: "keyword_#elseif", matcher: "#elseif" },
  { type: "keyword_#else", matcher: "#else" },
  { type: "keyword_#for", matcher: "#for" },
  { type: "keyword_#value", matcher: "#value" },
  { type: "keyword_#id", matcher: "#id" },
  { type: "keyword_#code", matcher: "#code" },
  { type: "keyword_#eval", matcher: "#eval" },

  { type: "symbol_;", matcher: ";"},
  { type: "symbol_:", matcher: ":"},
  { type: "symbol_=", matcher: "=" },
  { type: "symbol_.", matcher: "." },
  { type: "symbol_->", matcher: "->"},
  { type: "symbol_(", matcher: "(" },
  { type: "symbol_)", matcher: ")" },
  { type: "symbol_,", matcher: "," },
  { type: "symbol_...", matcher: "..." },
  { type: "symbol_{", matcher: "{" },
  { type: "symbol_}", matcher: "}" },
  { type: "symbol_<", matcher: "<" },
  { type: "symbol_>", matcher: ">" },
  { type: "symbol_[", matcher: "[" },
  { type: "symbol_]", matcher: "]" },
  { type: "symbol_..", matcher: ".." },
  { type: "symbol_@", matcher: "@" },
  { type: "symbol_$", matcher: "$" },
  { type: "symbol_#<", matcher: "#<" },
  { type: "symbol_{{", matcher: "{{" },
  { type: "symbol_}}", matcher: "}}" },
  { type: "symbol_+", matcher: "+" },
  { type: "symbol_-", matcher: "-" },
  { type: "symbol_*", matcher: "*" },
  { type: "symbol_/", matcher: "/" },
  { type: "symbol_%", matcher: "%" },
  { type: "symbol_!", matcher: "!" },
  { type: "symbol_||", matcher: "||"},
  { type: "symbol_&&", matcher: "&&"},
  { type: "symbol_^", matcher: "^" },
  { type: "symbol_~", matcher: "~" },
  { type: "symbol_|", matcher: "|" },
  { type: "symbol_&", matcher: "&" },
  { type: "symbol_<<", matcher: "<<"},
  { type: "symbol_>>", matcher: ">>"},
  { type: "symbol_<", matcher: "<" },
  { type: "symbol_>", matcher: ">"},
  { type: "symbol_==", matcher: "==" },
  { type: "symbol_!=", matcher: "!=" },
  { type: "symbol_<=", matcher: "<="},
  { type: "symbol_>=", matcher: ">="},
  { type: "symbol_+=", matcher: "+=" },
  { type: "symbol_-=", matcher: "-="},
  { type: "symbol_*=", matcher: "*=" },
  { type: "symbol_/=", matcher: "/=" },
  { type: "symbol_%=", matcher: "%=" },
  { type: "symbol_^=", matcher: "^=" },
  { type: "symbol_~=", matcher: "~=" },
  { type: "symbol_|=", matcher: "|=" },
  { type: "symbol_&=", matcher: "&=" },
  { type: "symbol_<<=", matcher: "<<="},
  { type: "symbol_>>=", matcher: ">>="},

  { type: "literal_string", matcher: /^"([^"\\]|\\.)*"([ \t\r\n]*"([^"\\]|\\.)*")*/u },
  { type: "literal_char", matcher: /^'([^'\\]|\\.)'/u },
  { type: "literal_hex_integer", matcher: /^0x[0-9A-F]+(_[0-9A-F]+)*/u },
  { type: "literal_oct_integer", matcher: /^0o[0-7]+(_[0-7]+)*/u },
  { type: "literal_bin_integer", matcher: /^0b[01]+(_[01]+)*/u },
  { type: "literal_dec_integer", matcher: /^[0-9]+(_[0-9]+)*/u },
  { type: "literal_hex_float", matcher: /^0x([0-9A-F]+(_[0-9A-F]+)*\.[0-9A-F]+(_[0-9A-F]+)*)p-?[0-9]+/u },
  { type: "literal_dec_float", matcher: /^([0-9]+(_[0-9]+)*\.[0-9]+(_[0-9]+)*)(e-?[0-9]+)?/u },
  { type: "literal_bool", matcher: /^true|^false/u },
  { type: "literal_null", matcher: "null" },

  { type: "identifier", matcher: /^[A-Za-z_][0-9A-Za-z_]*/u },
]